# Generated by Django 4.1 on 2022-08-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='تسجيل_بيروت',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الحافظ', models.CharField(max_length=100)),
                ('الرواية', models.CharField(max_length=100)),
                ('الشيخ_المقرئ', models.CharField(max_length=100)),
                ('المركز', models.CharField(max_length=100)),
                ('لجنة_الاختبار', models.CharField(max_length=100)),
                ('النتيجة', models.CharField(max_length=100)),
                ('التاريخ', models.CharField(max_length=100)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='صيدا',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الحافظ', models.CharField(max_length=100)),
                ('الرواية', models.CharField(max_length=100)),
                ('الشيخ_المقرئ', models.CharField(max_length=100)),
                ('المركز', models.CharField(max_length=100)),
                ('لجنة_الاختبار', models.CharField(max_length=100)),
                ('النتيجة', models.CharField(max_length=100)),
                ('التاريخ', models.CharField(max_length=100)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='طرابلس',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الحافظ', models.CharField(max_length=100)),
                ('الرواية', models.CharField(max_length=100)),
                ('الشيخ_المقرئ', models.CharField(max_length=100)),
                ('المركز', models.CharField(max_length=100)),
                ('لجنة_الاختبار', models.CharField(max_length=100)),
                ('النتيجة', models.CharField(max_length=100)),
                ('التاريخ', models.CharField(max_length=100)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='عرمون',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الحافظ', models.CharField(max_length=100)),
                ('الرواية', models.CharField(max_length=100)),
                ('الشيخ_المقرئ', models.CharField(max_length=100)),
                ('المركز', models.CharField(max_length=100)),
                ('لجنة_الاختبار', models.CharField(max_length=100)),
                ('النتيجة', models.CharField(max_length=100)),
                ('التاريخ', models.CharField(max_length=100)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='عكار',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الحافظ', models.CharField(max_length=100)),
                ('الرواية', models.CharField(max_length=100)),
                ('الشيخ_المقرئ', models.CharField(max_length=100)),
                ('المركز', models.CharField(max_length=100)),
                ('لجنة_الاختبار', models.CharField(max_length=100)),
                ('النتيجة', models.CharField(max_length=100)),
                ('التاريخ', models.CharField(max_length=100)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
