# Generated by Django 4.1 on 2022-08-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('جدول_الحفظة_و_المجازين', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='تسجيل_بيروت',
            new_name='بيروت',
        ),
    ]
