# Generated by Django 4.1 on 2022-08-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('طلب_تدريس', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='صيدا',
            name='الرواية',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='صيدا',
            name='الشيخ_المجيز',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='صيدا',
            name='رواي_اتاخرى',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='طرابلس',
            name='الرواية',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='طرابلس',
            name='الشيخ_المجيز',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='طرابلس',
            name='رواي_اتاخرى',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='عرمون',
            name='الرواية',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='عرمون',
            name='الشيخ_المجيز',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='عرمون',
            name='رواي_اتاخرى',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='عكار',
            name='الرواية',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='عكار',
            name='الشيخ_المجيز',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='عكار',
            name='رواي_اتاخرى',
            field=models.TextField(blank=True, null=True),
        ),
    ]
