# Generated by Django 4.1 on 2022-08-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('طلب_تدريس', '0003_rename_رواي_اتاخرى_صيدا_روايات_اخرى_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='بيروت',
            name='ترغب_بالتدريس',
            field=models.CharField(choices=[('ببدل', 'ببدل'), ('تطوع', 'تطوع')], default='ببدل', max_length=10),
        ),
        migrations.AlterField(
            model_name='صيدا',
            name='ترغب_بالتدريس',
            field=models.CharField(choices=[('ببدل', 'ببدل'), ('تطوع', 'تطوع')], default='ببدل', max_length=10),
        ),
        migrations.AlterField(
            model_name='طرابلس',
            name='ترغب_بالتدريس',
            field=models.CharField(choices=[('ببدل', 'ببدل'), ('تطوع', 'تطوع')], default='ببدل', max_length=10),
        ),
        migrations.AlterField(
            model_name='عرمون',
            name='ترغب_بالتدريس',
            field=models.CharField(choices=[('ببدل', 'ببدل'), ('تطوع', 'تطوع')], default='ببدل', max_length=10),
        ),
        migrations.AlterField(
            model_name='عكار',
            name='ترغب_بالتدريس',
            field=models.CharField(choices=[('ببدل', 'ببدل'), ('تطوع', 'تطوع')], default='ببدل', max_length=10),
        ),
    ]
