# Generated by Django 4.1 on 2022-08-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('الحضور', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='بيروت',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم', models.TextField(blank=True, null=True)),
                ('الحضور', models.CharField(blank=True, choices=[('حاضر', 'حاضر'), ('غائب', 'غائب')], max_length=8)),
                ('مكان_الحفظ', models.TextField(blank=True, null=True)),
                ('مكان_المراجعة', models.TextField(blank=True, null=True)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='صيدا',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم', models.TextField(blank=True, null=True)),
                ('الحضور', models.CharField(blank=True, choices=[('حاضر', 'حاضر'), ('غائب', 'غائب')], max_length=8)),
                ('مكان_الحفظ', models.TextField(blank=True, null=True)),
                ('مكان_المراجعة', models.TextField(blank=True, null=True)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='طرابلس',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم', models.TextField(blank=True, null=True)),
                ('الحضور', models.CharField(blank=True, choices=[('حاضر', 'حاضر'), ('غائب', 'غائب')], max_length=8)),
                ('مكان_الحفظ', models.TextField(blank=True, null=True)),
                ('مكان_المراجعة', models.TextField(blank=True, null=True)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='عرمون',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم', models.TextField(blank=True, null=True)),
                ('الحضور', models.CharField(blank=True, choices=[('حاضر', 'حاضر'), ('غائب', 'غائب')], max_length=8)),
                ('مكان_الحفظ', models.TextField(blank=True, null=True)),
                ('مكان_المراجعة', models.TextField(blank=True, null=True)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='عكار',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم', models.TextField(blank=True, null=True)),
                ('الحضور', models.CharField(blank=True, choices=[('حاضر', 'حاضر'), ('غائب', 'غائب')], max_length=8)),
                ('مكان_الحفظ', models.TextField(blank=True, null=True)),
                ('مكان_المراجعة', models.TextField(blank=True, null=True)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='الحضور',
        ),
    ]
