# Generated by Django 4.1 on 2022-08-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='بيروت',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الطالب', models.CharField(default='-', max_length=1000)),
                ('اعضاء_اللجنة', models.CharField(default='-', max_length=1000)),
                ('قرأت_ختمة_كاملة_ب', models.CharField(default=' ', max_length=1000)),
                ('من_طريي', models.CharField(default='-', max_length=1000)),
                ('على', models.CharField(default=' ', max_length=1000)),
                ('مركز', models.CharField(default='-', max_length=1000)),
                ('الاختبار_في_الاجزاء', models.CharField(default='-', max_length=1000)),
                ('مجموع_الدرجات_من_١٠٠', models.CharField(default='-', max_length=1000)),
                ('قرار_اللجنة', models.CharField(default='-', max_length=10000)),
                ('ملاحظات', models.CharField(default='-', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='صيدا',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الطالب', models.CharField(default='-', max_length=1000)),
                ('اعضاء_اللجنة', models.CharField(default='-', max_length=1000)),
                ('قرأت_ختمة_كاملة_ب', models.CharField(default=' ', max_length=1000)),
                ('من_طريي', models.CharField(default='-', max_length=1000)),
                ('على', models.CharField(default=' ', max_length=1000)),
                ('مركز', models.CharField(default='-', max_length=1000)),
                ('الاختبار_في_الاجزاء', models.CharField(default='-', max_length=1000)),
                ('مجموع_الدرجات_من_١٠٠', models.CharField(default='-', max_length=1000)),
                ('قرار_اللجنة', models.CharField(default='-', max_length=10000)),
                ('ملاحظات', models.CharField(default='-', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='طرابلس',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الطالب', models.CharField(default='-', max_length=1000)),
                ('اعضاء_اللجنة', models.CharField(default='-', max_length=1000)),
                ('قرأت_ختمة_كاملة_ب', models.CharField(default=' ', max_length=1000)),
                ('من_طريي', models.CharField(default='-', max_length=1000)),
                ('على', models.CharField(default=' ', max_length=1000)),
                ('مركز', models.CharField(default='-', max_length=1000)),
                ('الاختبار_في_الاجزاء', models.CharField(default='-', max_length=1000)),
                ('مجموع_الدرجات_من_١٠٠', models.CharField(default='-', max_length=1000)),
                ('قرار_اللجنة', models.CharField(default='-', max_length=10000)),
                ('ملاحظات', models.CharField(default='-', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='عرمون',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الطالب', models.CharField(default='-', max_length=1000)),
                ('اعضاء_اللجنة', models.CharField(default='-', max_length=1000)),
                ('قرأت_ختمة_كاملة_ب', models.CharField(default=' ', max_length=1000)),
                ('من_طريي', models.CharField(default='-', max_length=1000)),
                ('على', models.CharField(default=' ', max_length=1000)),
                ('مركز', models.CharField(default='-', max_length=1000)),
                ('الاختبار_في_الاجزاء', models.CharField(default='-', max_length=1000)),
                ('مجموع_الدرجات_من_١٠٠', models.CharField(default='-', max_length=1000)),
                ('قرار_اللجنة', models.CharField(default='-', max_length=10000)),
                ('ملاحظات', models.CharField(default='-', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='عكار',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الطالب', models.CharField(default='-', max_length=1000)),
                ('اعضاء_اللجنة', models.CharField(default='-', max_length=1000)),
                ('قرأت_ختمة_كاملة_ب', models.CharField(default=' ', max_length=1000)),
                ('من_طريي', models.CharField(default='-', max_length=1000)),
                ('على', models.CharField(default=' ', max_length=1000)),
                ('مركز', models.CharField(default='-', max_length=1000)),
                ('الاختبار_في_الاجزاء', models.CharField(default='-', max_length=1000)),
                ('مجموع_الدرجات_من_١٠٠', models.CharField(default='-', max_length=1000)),
                ('قرار_اللجنة', models.CharField(default='-', max_length=10000)),
                ('ملاحظات', models.CharField(default='-', max_length=1000)),
            ],
        ),
    ]
