# Generated by Django 4.1 on 2022-08-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('منح_اجازة', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='بيروت',
            name='من_طريي',
        ),
        migrations.RemoveField(
            model_name='صيدا',
            name='من_طريي',
        ),
        migrations.RemoveField(
            model_name='طرابلس',
            name='من_طريي',
        ),
        migrations.RemoveField(
            model_name='عرمون',
            name='من_طريي',
        ),
        migrations.RemoveField(
            model_name='عكار',
            name='من_طريي',
        ),
        migrations.AddField(
            model_name='بيروت',
            name='التاريخ',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='بيروت',
            name='من_طريق',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='صيدا',
            name='التاريخ',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='صيدا',
            name='من_طريق',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='طرابلس',
            name='التاريخ',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='طرابلس',
            name='من_طريق',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='عرمون',
            name='التاريخ',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='عرمون',
            name='من_طريق',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='عكار',
            name='التاريخ',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='عكار',
            name='من_طريق',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='بيروت',
            name='اسم_الطالب',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='بيروت',
            name='اعضاء_اللجنة',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='بيروت',
            name='الاختبار_في_الاجزاء',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='بيروت',
            name='قرار_اللجنة',
            field=models.CharField(default=' ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='بيروت',
            name='مجموع_الدرجات_من_١٠٠',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='بيروت',
            name='مركز',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='بيروت',
            name='ملاحظات',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='صيدا',
            name='اسم_الطالب',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='صيدا',
            name='اعضاء_اللجنة',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='صيدا',
            name='الاختبار_في_الاجزاء',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='صيدا',
            name='قرار_اللجنة',
            field=models.CharField(default=' ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='صيدا',
            name='مجموع_الدرجات_من_١٠٠',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='صيدا',
            name='مركز',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='صيدا',
            name='ملاحظات',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='طرابلس',
            name='اسم_الطالب',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='طرابلس',
            name='اعضاء_اللجنة',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='طرابلس',
            name='الاختبار_في_الاجزاء',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='طرابلس',
            name='قرار_اللجنة',
            field=models.CharField(default=' ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='طرابلس',
            name='مجموع_الدرجات_من_١٠٠',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='طرابلس',
            name='مركز',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='طرابلس',
            name='ملاحظات',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='عرمون',
            name='اسم_الطالب',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='عرمون',
            name='اعضاء_اللجنة',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='عرمون',
            name='الاختبار_في_الاجزاء',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='عرمون',
            name='قرار_اللجنة',
            field=models.CharField(default=' ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='عرمون',
            name='مجموع_الدرجات_من_١٠٠',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='عرمون',
            name='مركز',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='عرمون',
            name='ملاحظات',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='عكار',
            name='اسم_الطالب',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='عكار',
            name='اعضاء_اللجنة',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='عكار',
            name='الاختبار_في_الاجزاء',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='عكار',
            name='قرار_اللجنة',
            field=models.CharField(default=' ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='عكار',
            name='مجموع_الدرجات_من_١٠٠',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='عكار',
            name='مركز',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='عكار',
            name='ملاحظات',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
