# Generated by Django 4.1 on 2022-08-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='تسجيل_بيروت',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم_الثلاثي', models.CharField(max_length=200)),
                ('مهنة_الاب', models.CharField(max_length=100)),
                ('الهاتف', models.IntegerField()),
                ('تاريخ_الميلاد', models.CharField(max_length=100)),
                ('العمر', models.IntegerField()),
                ('اسم_الام', models.CharField(max_length=100)),
                ('مهنة_الام', models.CharField(max_length=100)),
                ('هاتف_الام', models.IntegerField()),
                ('الجنسية', models.CharField(max_length=100)),
                ('المدرسة_او_الجامعة', models.CharField(max_length=100)),
                ('الصف_او_التخصص', models.CharField(max_length=100)),
                ('التقدير', models.CharField(max_length=100)),
            ],
        ),
    ]
