# Generated by Django 4.1 on 2022-08-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('تسجيل_بيروت', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='تسجيل_بيروت',
            name='محفوظاته_من_القران',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AddField(
            model_name='تسجيل_بيروت',
            name='مستوى_القراءة_بالقران',
            field=models.CharField(choices=[('مبتدئ', 'مبتدئ'), ('قارئ', 'قارئ'), ('حافظ', 'حافظ'), ('مجاز', 'مجاز')], default='مبتدئ', max_length=10),
        ),
    ]
