# Generated by Django 4.1 on 2022-08-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('تسجيل_بيروت', '0002_تسجيل_بيروت_محفوظاته_من_القران_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='تسجيل_بيروت',
            name='الاسم_الثلاثي',
        ),
    ]
