# Generated by Django 4.1 on 2022-08-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('تسجيل_بيروت', '0005_تسجيل_صيدا_تسجيل_طرابلس_تسجيل_عرمون_تسجيل_عكار'),
    ]

    operations = [
        migrations.AddField(
            model_name='تسجيل_صيدا',
            name='التاريخ',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='تسجيل_طرابلس',
            name='التاريخ',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='تسجيل_عرمون',
            name='التاريخ',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='تسجيل_عكار',
            name='التاريخ',
            field=models.DateField(auto_now=True),
        ),
    ]
