# Generated by Django 4.1 on 2022-08-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='بيروت',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الدورة_او_المدرسة', models.CharField(default='-', max_length=1000)),
                ('اسم_المدير_او_المشرف', models.CharField(default='-', max_length=1000)),
                ('العنوان', models.CharField(default=' ', max_length=1000)),
                ('هاتف', models.CharField(default='-', max_length=1000)),
                ('تاريخ_تقديم_الطلب', models.CharField(default=' ', max_length=1000)),
                ('الكمية_المطلوبة_جزء_عم', models.CharField(default='-', max_length=1000)),
                ('الكمية_المطلوبة_جزء_تبارك', models.CharField(default='-', max_length=1000)),
                ('الكمية_المطلوبة_جزء_قد_سمع', models.CharField(default='-', max_length=1000)),
                ('تاريخ_الاستلام', models.CharField(default='-', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='صيدا',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الدورة_او_المدرسة', models.CharField(default='-', max_length=1000)),
                ('اسم_المدير_او_المشرف', models.CharField(default='-', max_length=1000)),
                ('العنوان', models.CharField(default=' ', max_length=1000)),
                ('هاتف', models.CharField(default='-', max_length=1000)),
                ('تاريخ_تقديم_الطلب', models.CharField(default=' ', max_length=1000)),
                ('الكمية_المطلوبة_جزء_عم', models.CharField(default='-', max_length=1000)),
                ('الكمية_المطلوبة_جزء_تبارك', models.CharField(default='-', max_length=1000)),
                ('الكمية_المطلوبة_جزء_قد_سمع', models.CharField(default='-', max_length=1000)),
                ('تاريخ_الاستلام', models.CharField(default='-', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='طرابلس',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الدورة_او_المدرسة', models.CharField(default='-', max_length=1000)),
                ('اسم_المدير_او_المشرف', models.CharField(default='-', max_length=1000)),
                ('العنوان', models.CharField(default=' ', max_length=1000)),
                ('هاتف', models.CharField(default='-', max_length=1000)),
                ('تاريخ_تقديم_الطلب', models.CharField(default=' ', max_length=1000)),
                ('الكمية_المطلوبة_جزء_عم', models.CharField(default='-', max_length=1000)),
                ('الكمية_المطلوبة_جزء_تبارك', models.CharField(default='-', max_length=1000)),
                ('الكمية_المطلوبة_جزء_قد_سمع', models.CharField(default='-', max_length=1000)),
                ('تاريخ_الاستلام', models.CharField(default='-', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='عرمون',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الدورة_او_المدرسة', models.CharField(default='-', max_length=1000)),
                ('اسم_المدير_او_المشرف', models.CharField(default='-', max_length=1000)),
                ('العنوان', models.CharField(default=' ', max_length=1000)),
                ('هاتف', models.CharField(default='-', max_length=1000)),
                ('تاريخ_تقديم_الطلب', models.CharField(default=' ', max_length=1000)),
                ('الكمية_المطلوبة_جزء_عم', models.CharField(default='-', max_length=1000)),
                ('الكمية_المطلوبة_جزء_تبارك', models.CharField(default='-', max_length=1000)),
                ('الكمية_المطلوبة_جزء_قد_سمع', models.CharField(default='-', max_length=1000)),
                ('تاريخ_الاستلام', models.CharField(default='-', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='عكار',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_الدورة_او_المدرسة', models.CharField(default='-', max_length=1000)),
                ('اسم_المدير_او_المشرف', models.CharField(default='-', max_length=1000)),
                ('العنوان', models.CharField(default=' ', max_length=1000)),
                ('هاتف', models.CharField(default='-', max_length=1000)),
                ('تاريخ_تقديم_الطلب', models.CharField(default=' ', max_length=1000)),
                ('الكمية_المطلوبة_جزء_عم', models.CharField(default='-', max_length=1000)),
                ('الكمية_المطلوبة_جزء_تبارك', models.CharField(default='-', max_length=1000)),
                ('الكمية_المطلوبة_جزء_قد_سمع', models.CharField(default='-', max_length=1000)),
                ('تاريخ_الاستلام', models.CharField(default='-', max_length=1000)),
            ],
        ),
    ]
