# Generated by Django 4.1 on 2022-08-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='بيروت',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اليوم', models.CharField(max_length=1000)),
                ('التاريخ', models.CharField(max_length=1000)),
                ('البديل', models.CharField(max_length=1000)),
                ('اسم_الموظف', models.CharField(max_length=1000)),
                ('سببالخروج', models.IntegerField()),
                ('اذن_خروج_خلالالعمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('اذن_للتأخر_عن_العمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('اذن_خروج_لترك_العمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('عددالساعات', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='صيدا',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اليوم', models.CharField(max_length=1000)),
                ('التاريخ', models.CharField(max_length=1000)),
                ('البديل', models.CharField(max_length=1000)),
                ('اسم_الموظف', models.CharField(max_length=1000)),
                ('سببالخروج', models.IntegerField()),
                ('اذن_خروج_خلالالعمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('اذن_للتأخر_عن_العمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('اذن_خروج_لترك_العمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('عددالساعات', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='طرابلس',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اليوم', models.CharField(max_length=1000)),
                ('التاريخ', models.CharField(max_length=1000)),
                ('البديل', models.CharField(max_length=1000)),
                ('اسم_الموظف', models.CharField(max_length=1000)),
                ('سببالخروج', models.IntegerField()),
                ('اذن_خروج_خلالالعمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('اذن_للتأخر_عن_العمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('اذن_خروج_لترك_العمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('عددالساعات', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='عرمون',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اليوم', models.CharField(max_length=1000)),
                ('التاريخ', models.CharField(max_length=1000)),
                ('البديل', models.CharField(max_length=1000)),
                ('اسم_الموظف', models.CharField(max_length=1000)),
                ('سببالخروج', models.IntegerField()),
                ('اذن_خروج_خلالالعمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('اذن_للتأخر_عن_العمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('اذن_خروج_لترك_العمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('عددالساعات', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='عكار',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اليوم', models.CharField(max_length=1000)),
                ('التاريخ', models.CharField(max_length=1000)),
                ('البديل', models.CharField(max_length=1000)),
                ('اسم_الموظف', models.CharField(max_length=1000)),
                ('سببالخروج', models.IntegerField()),
                ('اذن_خروج_خلالالعمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('اذن_للتأخر_عن_العمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('اذن_خروج_لترك_العمل_من_الى', models.CharField(default='-', max_length=1000)),
                ('عددالساعات', models.IntegerField()),
            ],
        ),
    ]
