# Generated by Django 4.1 on 2022-08-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('اذن_خروج_او_تاخر', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='بيروت',
            old_name='سببالخروج',
            new_name='عدد_الساعات',
        ),
        migrations.RenameField(
            model_name='صيدا',
            old_name='سببالخروج',
            new_name='عدد_الساعات',
        ),
        migrations.RenameField(
            model_name='طرابلس',
            old_name='سببالخروج',
            new_name='عدد_الساعات',
        ),
        migrations.RenameField(
            model_name='عرمون',
            old_name='سببالخروج',
            new_name='عدد_الساعات',
        ),
        migrations.RenameField(
            model_name='عكار',
            old_name='سببالخروج',
            new_name='عدد_الساعات',
        ),
        migrations.RemoveField(
            model_name='بيروت',
            name='عددالساعات',
        ),
        migrations.RemoveField(
            model_name='صيدا',
            name='عددالساعات',
        ),
        migrations.RemoveField(
            model_name='طرابلس',
            name='عددالساعات',
        ),
        migrations.RemoveField(
            model_name='عرمون',
            name='عددالساعات',
        ),
        migrations.RemoveField(
            model_name='عكار',
            name='عددالساعات',
        ),
        migrations.AddField(
            model_name='بيروت',
            name='القسم',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='بيروت',
            name='سبب_الخروج',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='صيدا',
            name='القسم',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='صيدا',
            name='سبب_الخروج',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='طرابلس',
            name='القسم',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='طرابلس',
            name='سبب_الخروج',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='عرمون',
            name='القسم',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='عرمون',
            name='سبب_الخروج',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='عكار',
            name='القسم',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='عكار',
            name='سبب_الخروج',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
