# Generated by Django 4.1 on 2022-08-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='بيروت',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_المدرس', models.CharField(default=' ', max_length=1000)),
                ('اسم_الطالب', models.CharField(default=' ', max_length=1000)),
                ('تاريخ_بدء_برنامج_الضبط', models.CharField(default=' ', max_length=1000)),
                ('المدة', models.CharField(default=' ', max_length=1000)),
                ('الرواية', models.CharField(default=' ', max_length=1000)),
                ('تاريخ_الاختبار', models.CharField(default=' ', max_length=1000)),
                ('من_الى', models.CharField(default=' ', max_length=1000)),
                ('التقدير', models.CharField(default=' ', max_length=1000)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='صيدا',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_المدرس', models.CharField(default=' ', max_length=1000)),
                ('اسم_الطالب', models.CharField(default=' ', max_length=1000)),
                ('تاريخ_بدء_برنامج_الضبط', models.CharField(default=' ', max_length=1000)),
                ('المدة', models.CharField(default=' ', max_length=1000)),
                ('الرواية', models.CharField(default=' ', max_length=1000)),
                ('تاريخ_الاختبار', models.CharField(default=' ', max_length=1000)),
                ('من_الى', models.CharField(default=' ', max_length=1000)),
                ('التقدير', models.CharField(default=' ', max_length=1000)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='طرابلس',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_المدرس', models.CharField(default=' ', max_length=1000)),
                ('اسم_الطالب', models.CharField(default=' ', max_length=1000)),
                ('تاريخ_بدء_برنامج_الضبط', models.CharField(default=' ', max_length=1000)),
                ('المدة', models.CharField(default=' ', max_length=1000)),
                ('الرواية', models.CharField(default=' ', max_length=1000)),
                ('تاريخ_الاختبار', models.CharField(default=' ', max_length=1000)),
                ('من_الى', models.CharField(default=' ', max_length=1000)),
                ('التقدير', models.CharField(default=' ', max_length=1000)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='عرمون',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_المدرس', models.CharField(default=' ', max_length=1000)),
                ('اسم_الطالب', models.CharField(default=' ', max_length=1000)),
                ('تاريخ_بدء_برنامج_الضبط', models.CharField(default=' ', max_length=1000)),
                ('المدة', models.CharField(default=' ', max_length=1000)),
                ('الرواية', models.CharField(default=' ', max_length=1000)),
                ('تاريخ_الاختبار', models.CharField(default=' ', max_length=1000)),
                ('من_الى', models.CharField(default=' ', max_length=1000)),
                ('التقدير', models.CharField(default=' ', max_length=1000)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='عكار',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_المدرس', models.CharField(default=' ', max_length=1000)),
                ('اسم_الطالب', models.CharField(default=' ', max_length=1000)),
                ('تاريخ_بدء_برنامج_الضبط', models.CharField(default=' ', max_length=1000)),
                ('المدة', models.CharField(default=' ', max_length=1000)),
                ('الرواية', models.CharField(default=' ', max_length=1000)),
                ('تاريخ_الاختبار', models.CharField(default=' ', max_length=1000)),
                ('من_الى', models.CharField(default=' ', max_length=1000)),
                ('التقدير', models.CharField(default=' ', max_length=1000)),
                ('ملاحظات', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
