from django.db import models

# Create your models here.
class بيروت(models.Model):
    الاسم_الثلاثي= models.CharField(max_length=200)
    مهنة_الاب = models.CharField(max_length=100)
    الهاتف= models.IntegerField()
    تاريخ_الميلا = models.CharField(max_length=100)
    العمر = models.IntegerField()
    اسم_الام= models.CharField(max_length=100)
    مهنة_الام = models.CharField(max_length=100)
    هاتف_الام = models.IntegerField()
    الجنسية= models.CharField(max_length=100)
    المدرسة= models.CharField(max_length=100)
    الصف= models.CharField(max_length=100)
    التقدير= models.CharField(max_length=100)
    محفوظاته_من_القران = models.CharField(max_length=300)

class طرابلس(models.Model):
    الاسم_الثلاثي= models.CharField(max_length=200)
    مهنة_الاب = models.CharField(max_length=100)
    الهاتف= models.IntegerField()
    تاريخ_الميلا = models.CharField(max_length=100)
    العمر = models.IntegerField()
    اسم_الام= models.CharField(max_length=100)
    مهنة_الام = models.CharField(max_length=100)
    هاتف_الام = models.IntegerField()
    الجنسية= models.CharField(max_length=100)
    المدرسة= models.CharField(max_length=100)
    الصف= models.CharField(max_length=100)
    التقدير= models.CharField(max_length=100)
    محفوظاته_من_القران = models.CharField(max_length=300)

class عكار(models.Model):
    الاسم_الثلاثي= models.CharField(max_length=200)
    مهنة_الاب = models.CharField(max_length=100)
    الهاتف= models.IntegerField()
    تاريخ_الميلا = models.CharField(max_length=100)
    العمر = models.IntegerField()
    اسم_الام= models.CharField(max_length=100)
    مهنة_الام = models.CharField(max_length=100)
    هاتف_الام = models.IntegerField()
    الجنسية= models.CharField(max_length=100)
    المدرسة= models.CharField(max_length=100)
    الصف= models.CharField(max_length=100)
    التقدير= models.CharField(max_length=100)
    محفوظاته_من_القران = models.CharField(max_length=300)

class عرمون(models.Model):
    الاسم_الثلاثي= models.CharField(max_length=200)
    مهنة_الاب = models.CharField(max_length=100)
    الهاتف= models.IntegerField()
    تاريخ_الميلا = models.CharField(max_length=100)
    العمر = models.IntegerField()
    اسم_الام= models.CharField(max_length=100)
    مهنة_الام = models.CharField(max_length=100)
    هاتف_الام = models.IntegerField()
    الجنسية= models.CharField(max_length=100)
    المدرسة= models.CharField(max_length=100)
    الصف= models.CharField(max_length=100)
    التقدير= models.CharField(max_length=100)
    محفوظاته_من_القران = models.CharField(max_length=300)

class صيدا(models.Model):
    الاسم_الثلاثي= models.CharField(max_length=200)
    مهنة_الاب = models.CharField(max_length=100)
    الهاتف= models.IntegerField()
    تاريخ_الميلا = models.CharField(max_length=100)
    العمر = models.IntegerField()
    اسم_الام= models.CharField(max_length=100)
    مهنة_الام = models.CharField(max_length=100)
    هاتف_الام = models.IntegerField()
    الجنسية= models.CharField(max_length=100)
    المدرسة= models.CharField(max_length=100)
    الصف= models.CharField(max_length=100)
    التقدير= models.CharField(max_length=100)
    محفوظاته_من_القران = models.CharField(max_length=300)
