# Generated by Django 4.1 on 2022-08-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('جيل_القران', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='صيدا',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم_الثلاثي', models.CharField(max_length=200)),
                ('مهنة_الاب', models.CharField(max_length=100)),
                ('الهاتف', models.IntegerField()),
                ('تاريخ_الميلا', models.CharField(max_length=100)),
                ('العمر', models.IntegerField()),
                ('اسم_الام', models.CharField(max_length=100)),
                ('مهنة_الام', models.CharField(max_length=100)),
                ('هاتف_الام', models.IntegerField()),
                ('الجنسية', models.CharField(max_length=100)),
                ('المدرسة', models.CharField(max_length=100)),
                ('الصف', models.CharField(max_length=100)),
                ('التقدير', models.CharField(max_length=100)),
                ('محفوظاته_من_القران', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='طرابلس',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم_الثلاثي', models.CharField(max_length=200)),
                ('مهنة_الاب', models.CharField(max_length=100)),
                ('الهاتف', models.IntegerField()),
                ('تاريخ_الميلا', models.CharField(max_length=100)),
                ('العمر', models.IntegerField()),
                ('اسم_الام', models.CharField(max_length=100)),
                ('مهنة_الام', models.CharField(max_length=100)),
                ('هاتف_الام', models.IntegerField()),
                ('الجنسية', models.CharField(max_length=100)),
                ('المدرسة', models.CharField(max_length=100)),
                ('الصف', models.CharField(max_length=100)),
                ('التقدير', models.CharField(max_length=100)),
                ('محفوظاته_من_القران', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='عرمون',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم_الثلاثي', models.CharField(max_length=200)),
                ('مهنة_الاب', models.CharField(max_length=100)),
                ('الهاتف', models.IntegerField()),
                ('تاريخ_الميلا', models.CharField(max_length=100)),
                ('العمر', models.IntegerField()),
                ('اسم_الام', models.CharField(max_length=100)),
                ('مهنة_الام', models.CharField(max_length=100)),
                ('هاتف_الام', models.IntegerField()),
                ('الجنسية', models.CharField(max_length=100)),
                ('المدرسة', models.CharField(max_length=100)),
                ('الصف', models.CharField(max_length=100)),
                ('التقدير', models.CharField(max_length=100)),
                ('محفوظاته_من_القران', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='عكار',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم_الثلاثي', models.CharField(max_length=200)),
                ('مهنة_الاب', models.CharField(max_length=100)),
                ('الهاتف', models.IntegerField()),
                ('تاريخ_الميلا', models.CharField(max_length=100)),
                ('العمر', models.IntegerField()),
                ('اسم_الام', models.CharField(max_length=100)),
                ('مهنة_الام', models.CharField(max_length=100)),
                ('هاتف_الام', models.IntegerField()),
                ('الجنسية', models.CharField(max_length=100)),
                ('المدرسة', models.CharField(max_length=100)),
                ('الصف', models.CharField(max_length=100)),
                ('التقدير', models.CharField(max_length=100)),
                ('محفوظاته_من_القران', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='جيل_القران',
            new_name='بيروت',
        ),
    ]
